version: "3"
services:
  laravelapp:
    build: . 
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - internal
  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge
